<?xml version="1.0" encoding="utf-8"?>
<!-- Generator: Adobe Illustrator 27.3.1, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
<svg version="1.1" id="Layer_2_00000160894217455783498110000007241275602178007183_"
	 xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 107.9 123.6"
	 style="enable-background:new 0 0 107.9 123.6;" xml:space="preserve">
<style type="text/css">
	.st0{fill:url(#SVGID_1_);}
</style>
<g>
	
		<linearGradient id="SVGID_1_" gradientUnits="userSpaceOnUse" x1="53.95" y1="101.2239" x2="53.95" y2="27.1761" gradientTransform="matrix(1 0 0 -1 0 126)">
		<stop  offset="0" style="stop-color:#F2D488"/>
		<stop  offset="1" style="stop-color:#FFFFFF"/>
	</linearGradient>
	<path class="st0" d="M73.2,65.8l1.2-20.7h-1.3L54,83.2l-19-38.1h-1.3l1.2,20.7v32.9H15.6v-74h26l12.6,25h1.2l12.6-25h24.2v74h-19
		V65.8z"/>
</g>
</svg>
